name: Build and Deploy Vaadin App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (Production Mode)
        run: mvn clean package -Pproduction -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaadin-app
          path: target/*.jar
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vaadin-app
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to DigitalOcean Droplet
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          # Finde die JAR-Datei
          JAR_FILE=$(ls *.jar | head -1)
          echo "Deploying JAR file: $JAR_FILE"
          
          # Stoppe die existierende Anwendung
          echo "Stopping existing application..."
          ssh $DROPLET_USER@$DROPLET_HOST 'sudo systemctl stop vaadin-app || echo "Service was not running"'
          
          # Erstelle Backup der alten Version
          echo "Creating backup of old version..."
          ssh $DROPLET_USER@$DROPLET_HOST 'sudo cp /opt/vaadin-app/app.jar /opt/vaadin-app/app.jar.backup 2>/dev/null || echo "No previous version found"'
          
          # Lade neue JAR-Datei hoch
          echo "Uploading new JAR file..."
          scp $JAR_FILE $DROPLET_USER@$DROPLET_HOST:/tmp/app.jar
          
          # Verschiebe JAR-Datei an den finalen Ort und setze Berechtigungen
          echo "Installing new version..."
          ssh $DROPLET_USER@$DROPLET_HOST 'sudo mv /tmp/app.jar /opt/vaadin-app/app.jar && sudo chown vaadin-app:vaadin-app /opt/vaadin-app/app.jar && sudo chmod +x /opt/vaadin-app/app.jar'
          
          # Starte die Anwendung
          echo "Starting application..."
          ssh $DROPLET_USER@$DROPLET_HOST 'sudo systemctl start vaadin-app'
          
          # Warte kurz und überprüfe den Status
          sleep 5
          echo "Checking application status..."
          ssh $DROPLET_USER@$DROPLET_HOST 'sudo systemctl status vaadin-app --no-pager'
          
          echo "Deployment completed successfully!"