name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Debug SSH Key Format
      run: |
        echo "=== SSH Key Debug ==="
        echo "Key length: ${#SSH_PRIVATE_KEY}"
        echo "First line: $(echo "$SSH_PRIVATE_KEY" | head -1)"
        echo "Last line: $(echo "$SSH_PRIVATE_KEY" | tail -1)"
        echo "Line count: $(echo "$SSH_PRIVATE_KEY" | wc -l)"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} 'echo "SSH Test erfolgreich!"'